feat(discord): improvements
koishijs/koishi pull request #145
Opened 2021-03-02 12:58 UTC by XxLittleCxX

2021-03-03 15:01 UTC, Shigma requested changes

2021-03-03 15:19 UTC, XxLittleCxX commented on packages/adapter-discord/src/utils.ts
> +  session.timestamp = new Date(meta.timestamp).valueOf() || new Date().valueOf()
https://github.com/XxLittleCxX/koishi/blob/1450b16aa0d64f7f25b2608a16a22ed6efbaa0e7/packages/adapter-discord/src/utils.ts#L57

2021-03-04 07:42 UTC, Shigma requested changes
然后 conflict 处理一下，有冲突的地方按你写的来就行

2021-03-04 07:42 UTC, Shigma commented on packages/adapter-discord/src/index.ts
> +  interface UserInfo {
这个直接写进 koishi-core，去改 adapter.ts 那个文件

2021-03-04 10:05 UTC, XxLittleCxX commented on packages/adapter-discord/src/index.ts
> +  interface UserInfo {
[`ef81f75` (#145)](https://github.com/koishijs/koishi/pull/145/commits/ef81f7554456924435c6553efc92f652be421e5e)

2021-03-04 10:15 UTC, merged