chore(discord): assign App.options.axiosConfig to bot.sendEmbedMessage
koishijs/koishi pull request #198
Opened 2021-04-01 18:46 UTC by Dragon-Fish

便于全局代理配置

2021-04-01 18:55 UTC, Shigma requested changes

2021-04-01 18:55 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +      ...this.app.options.axiosConfig,
建议尝试将 sendEmbedMessage 通过 request 实现，不写重复代码

discord 自己也有 axiosConfig 选项，请注意

2021-04-01 19:08 UTC, Shigma requested changes

2021-04-01 19:08 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +    const data = await this.reauest('POST', reauestUrl, fd, fd.getHeaders())
typo

2021-04-02 17:31 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +    const data = await this.reauest('POST', reauestUrl, fd, fd.getHeaders())
fixed

2021-04-02 18:10 UTC, Shigma approved these changes

2021-04-02 18:14 UTC, merged