feat(discord): functions
koishijs/koishi pull request #204
Opened 2021-04-03 11:11 UTC by XxLittleCxX

2021-04-03 12:52 UTC, Shigma requested changes

2021-04-03 12:52 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +} from './types'
上面好像已经有了 `import * as DC from './types'`？

2021-04-03 12:52 UTC, Shigma commented on packages/adapter-discord/src/types.ts
> +  name: string | null;
建议用 `name?: string` 代替 `name: string | null`，其他几处类似

2021-04-03 12:52 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $getGuildMember(guildId: string, userId: string) {
Koishi 协议已经定义的方法，建议直接实现成 Koishi 定义的不带 `$` 前缀的方法。

比如你可以这样写：

```js
const user = await this.request<GuildMember>('GET', `/guilds/${guildId}/members/${userId}`)
return DC.adaptGroupMember(user)
```

https://koishi.js.org/api/bot.html#bot-getgroupmember

2021-04-03 12:52 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $getChannel(channelId: string) {
https://koishi.js.org/api/bot.html#bot-getchannel

2021-04-03 12:52 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $listGuildMembers(guildId: string, limit?: number, after?: string) {
https://koishi.js.org/api/bot.html#bot-getgroupmemberlist

2021-04-03 12:57 UTC, XxLittleCxX commented on packages/adapter-discord/src/types.ts
> +  name: string | null;
文档中指的是这个value可能为null, 上面两个还是有点区别的吧

2021-04-03 12:59 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +  async $getGuildMember(guildId: string, userId: string) {
这里想用自定义方法的原因是有原生来自discord的类型，如果要实现koishi协议的话就加一层adapt，这个带`$`的前缀仍然保留，如何？

2021-04-03 12:59 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +  async $getGuildMember(guildId: string, userId: string) {
下面几个方法同理

2021-04-03 13:00 UTC, XxLittleCxX commented on packages/adapter-discord/src/types.ts
> +  name: string | null;
文档中指的是这个value可能为null, 上面两个还是有点区别的吧

Shigma: 有区别，但是关系不大。这涉及到一个 strictNullChecks 的问题。你的写法更严格，但目前 koishi 仓库其他地方都采用我建议的写法，统一有统一的好处。

2021-04-03 13:01 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +} from './types'
用ide爽了, 然后就忘了, will improve

2021-04-03 13:01 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $getGuildMember(guildId: string, userId: string) {
你当然可以同时实现两个方法：`$getGuildMember` 保留的同时加一个 `getGroupMember`。OneBot 也是这样做的。

2021-04-03 16:56 UTC, Shigma requested changes
此外，如果你的 typings 是爬网页生成而非手写的，那么我给两点建议：

1. 生成的 interface 前面加一行 URL
2. 补上一些常见的类型别名
3. 如果可以的话同时生成 jsdoc 注释

```js
type snowflake = string

/** https://discord.com/developers/docs/resources/channel#channel-object-channel-structure */
interface Channel {
  /** the id of this channel */
  id: snowflake
  /** the type of channel */
  type: ChannelType
}

enum ChannelType { GUILD_TEXT, DM, GUILD_VOICE }
```

如果 3 比较难做的话，至少把 1, 2 做好还是挺重要的。之后这里的 typings 肯定还要扩充，早做总比晚做来得好。

2021-04-03 16:56 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $modifyGuildMember(guildId: string, userId: string, data: {
这里的 data 用一个 interface 写看起来更好一些

2021-04-03 16:56 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +  async $modifyChannel(channelId, data: Pick<DC.Channel, 'name' | 'type' | 'position' | 'topic' | 'nsfw' | 'rate_limit_per_user' | 'bitrate' | 'user_limit' | 'permission_overwrites' | 'parent_id'>) {
同理，能否尽量改成 interface 的写法呢？

```js
interface ChannelConfig {
  name?: string
  type?: number
}

interface Channel extends ChannelConfig {
  id: string
}
```

个人建议，不强求（

2021-04-03 16:56 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> -  async getGroupList() {
这里为啥删掉？

2021-04-03 16:56 UTC, Shigma commented on packages/adapter-discord/src/types.ts
> +export interface GuildBody extends Pick<Guild, 'name' | 'region' | 'verification_level' | 'default_message_notifications' | 'explicit_content_filter' | 'afk_channel_id' | 'afk_timeout' | 'icon'| 'own
同上建议

2021-04-03 17:03 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> -  async getGroupList() {
丢到下面去了

2021-04-04 05:04 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +  async $modifyChannel(channelId, data: Pick<DC.Channel, 'name' | 'type' | 'position' | 'topic' | 'nsfw' | 'rate_limit_per_user' | 'bitrate' | 'user_limit' | 'permission_overwrites' | 'parent_id'>) {
我觉得这么长一个interface拆开有点混乱, 函数上面留个PATH的注释就行了

2021-04-04 05:04 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +  async $modifyChannel(channelId, data: Pick<DC.Channel, 'name' | 'type' | 'position' | 'topic' | 'nsfw' | 'rate_limit_per_user' | 'bitrate' | 'user_limit' | 'permission_overwrites' | 'parent_id'>) {
或者把这个参数的type单独export一下, 我试试

2021-04-04 05:29 UTC, Shigma approved these changes

2021-04-04 12:13 UTC, merged