fix(discord): improvements
koishijs/koishi pull request #212
Opened 2021-04-07 13:32 UTC by XxLittleCxX

2021-04-07 17:35 UTC, Shigma requested changes

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +export class SenderError extends Error {
于是乎这个 1.0 时期就有的古董类被你们抄进了每一个 adapter……我已经开始考虑要不要直接从 koishi-core 导出了……当然不是这个 PR 该干的事情就是了，我随便吐槽而已。

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/index.ts
> +      raw: any
改 any 的地方给个解释，或者在代码里或者在这个 PR 里都可以。

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/types.ts
> +  allowed_mentions?: Partial<AllowedMention>[]
既然这里要 Partial 为什么上面不 `?:` 呢

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/utils.ts
> +    // if (!session.content) return
这里的注释给个理由，代码里或者 PR 里都行。

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/index.ts
> +      raw: any
如果可能是多种格式的 union，可以用 `|` 解决？

不然单独一个 raw 的话，使用者也无法得知任何信息啊……

2021-04-07 17:35 UTC, Shigma commented on packages/adapter-discord/src/utils.ts
> +  session.discord = {
这里，如果这么写就会被 schedule 等插件序列化。我不确定这里是否一定需要序列化。如果不是一定的话，那么建议改成下面的写法：

```js
// 这个函数从 koishi-utils 导入
defineProperty(session, 'discord', {})
```

2021-04-07 17:37 UTC, Shigma commented on packages/adapter-discord/src/index.ts
> +      raw: any
顺便，这个文件头是不是有一个 unused import？

2021-04-07 22:40 UTC, XxLittleCxX commented on packages/adapter-discord/src/utils.ts
> +    // if (!session.content) return
你看下上下文，另一处相同的修改有注释

2021-04-07 22:41 UTC, XxLittleCxX commented on packages/adapter-discord/src/utils.ts
> +  session.discord = {
这个倒不是很确定，毕竟加raw本来就是想存一些session没法传的东西。

既然传了就当使用者需要这些值吧

2021-04-07 22:46 UTC, XxLittleCxX commented on packages/adapter-discord/src/index.ts
> +      raw: any
> 不然单独一个 raw 的话，使用者也无法得知任何信息啊……

这个本来是想union的，但是如果事件类型一多好像等于没有union，于是改成any让使用者自己处理了。大概可以`session.discord`上再加个type来推断一下不同的raw类型，有空试试。

2021-04-07 22:47 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +export class SenderError extends Error {
但我昨天加了个试了下发现没啥用，丢出来的还是axios又长又烂的exception，丢人

2021-04-10 05:27 UTC, Shigma approved these changes

2021-04-10 05:30 UTC, merged