feat(eval): support coffeescript
koishijs/koishi pull request #230
Opened 2021-04-14 13:14 UTC by Anillc

2021-04-14 15:12 UTC, Shigma requested changes
加个测试样例吧，fixture 里面写段 coffee

2021-04-14 16:45 UTC, Shigma reviewed
extractScript 我之后补个单测再说

2021-04-14 16:45 UTC, Shigma commented on packages/plugin-eval/src/loaders/coffeescript.ts
> +  return compile(expr, {bare: true})
code style: `{ bare: true }`

2021-04-15 10:21 UTC, Shigma commented
已更新代码。

1. 按照你的要求调整的 moduleLoader 后缀名的处理逻辑，请麻烦将 coffee 加在 ts 后面，json 前面。
2. 添加了 scriptLoader 单元测试，请补充 coffeescript 的部分。

辛苦了。

2021-04-15 16:30 UTC, Anillc commented
是否需要merge一下并解决冲突

2021-04-15 16:45 UTC, Shigma commented
y

2021-04-16 05:37 UTC, Shigma requested changes
jsx 属于 irrelevant feature，不应该被写进这个 pr

2021-04-17 04:34 UTC, Shigma approved these changes
LGTM

2021-04-17 04:34 UTC, merged