feat(discord): Optimize segment.image sending
koishijs/koishi pull request #282
Opened 2021-05-29 17:22 UTC by Dragon-Fish

#281 被我搞出了毛病，所以我重开了

2021-06-22 14:30 UTC, Shigma requested changes

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +            async function downloadSend() {
这里建议改成 sendDirect / sendDownloaded

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +            type SendMode = 'auto' | 'download' | 'direct'
这里的类型应该与 index.ts 中共用，可以考虑在这里定义然后 export 到 index.ts 中

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +              data.mode as SendMode || // define in segment
这里暂时先不加入正式的协议规范，我需要跟 onebot 团队讨论

删掉或者留着做后门都可以，但是如果留做后门的话我不保证这个接口在未来不会修改

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +              discord.handleExternalAssets as SendMode || // define in app options
看上面，共用了就不需要 as 了，甚至建议你放一行（

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +            type SendMode = 'auto' | 'download' | 'direct'
类型可以就是 HandleExternalAssets

2021-06-22 14:30 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +                .catch(async () => {
这里逻辑需要商榷，catch 会捕获 then 回调中的错误，所以应该是 `.then(A, B)` 而不是 `.then(A).catch(B)`

以及这里不应该是一定会有 headers 吗？

2021-06-22 14:44 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +              data.mode as SendMode || // define in segment
1. QQ 好像不支持直接发送链接，但是 onebot 现在好像不仅仅是 QQ 平台了，你可以去帮我提一下这个点
2. 这里的“后门”是有实用价值的，例如 smms 等图床直接 get 得到的是 html 而不是 image，此时如果直接发送链接反而能够看到图

2021-06-22 14:45 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +            async function downloadSend() {
done

2021-06-22 14:45 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +            type SendMode = 'auto' | 'download' | 'direct'
done

2021-06-22 14:47 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +              discord.handleExternalAssets as SendMode || // define in app options
不放一行是为了写注释，这里的 if 套的太多了，容易找不到变量是在哪里定义的

2021-06-22 14:50 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +                .catch(async () => {
done

2021-06-22 17:44 UTC, Shigma requested changes

2021-06-22 17:44 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +                try {
上面都没 catch，这里感觉应该统一，要么去掉 catch，要么在这里的 then 后面加一个 .catch 调用

2021-06-22 17:44 UTC, Shigma commented on packages/adapter-discord/src/index.ts
> +export type HandleExternalAssets = 'auto' | 'download' | 'direct'
建议把这个类型放到 bot.ts 中，逻辑组织上更好一些

2021-06-22 17:45 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +              data.mode as SendMode || // define in segment
我说的“不保证这个接口在未来不会修改”不是不保证不会删除，而是不保证会不会把 mode 换成别的词。你现在当然可以留着。

2021-06-22 17:46 UTC, Shigma commented on packages/adapter-discord/src/bot.ts
> +              data.mode as SendMode || // define in segment
顺便，smms get 的时候加个 accept 试试？也建议在这里的代码里加 accept header。

2021-06-23 10:42 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +                try {
done

2021-06-23 10:43 UTC, Dragon-Fish commented on packages/adapter-discord/src/index.ts
> +export type HandleExternalAssets = 'auto' | 'download' | 'direct'
done

2021-06-23 13:06 UTC, Shigma approved these changes

2021-06-23 17:39 UTC, merged