fix: recall is invalid on discord
koishijs/koishi pull request #284
Opened 2021-05-30 10:15 UTC by Dragon-Fish

- adapter-discord 在发送信息时不方便检查 subtype，所以我将 recall 里的选择器修改了一下
- adapter-discord 在 emit send 的时候忘记提供 messageId 了，我修了

2021-05-30 10:18 UTC, XxLittleCxX requested changes

2021-05-30 10:18 UTC, XxLittleCxX commented on packages/adapter-discord/src/bot.ts
> +    session.messageId = sentMessageId
你看这个和下面的重复了, 建议改改

2021-05-30 10:19 UTC, Dragon-Fish commented on packages/adapter-discord/src/bot.ts
> +    session.messageId = sentMessageId
已修改

2021-05-30 10:20 UTC, XxLittleCxX approved these changes

2021-05-30 12:41 UTC, Shigma reviewed
send 事件那部分没有问题。

没有 subtype 的问题本身值得重视，我更希望直接解决这个问题而不是对 recall 进行 patch。

如果急着合并的话可以只保留前一部分代码。

2021-05-30 12:46 UTC, Dragon-Fish commented
坐等 @XxLittleCxX 来解释一下为什么不方便提供 subtype

我记得对于 discord 来说，发送的时候私信和群聊都是 channel

2021-05-30 12:46 UTC, XxLittleCxX commented
确实

2021-05-30 12:47 UTC, Dragon-Fish commented
你是怎么做到秒回 issue 的

2021-05-30 12:48 UTC, XxLittleCxX commented
巧了, 我页面就开在这里

2021-05-30 12:49 UTC, Dragon-Fish commented
如果要获取 channel 是群聊还是私信，可能需要额外发送一次请求，这很阴间

2021-05-30 12:49 UTC, XxLittleCxX commented
@Shigma 催更一下缓存 api

2021-05-30 12:49 UTC, XxLittleCxX commented
你再不写我们就要写出社区插件了(

2021-05-30 12:52 UTC, Shigma commented
> 为什么不方便提供 subtype

@Dragon-Fish 这属于 Koishi 的 design limitation。我可能在 3.12 版本更新中修改一个 `bot.sendMessage` 函数的签名来解决问题。

2021-05-30 19:47 UTC, Shigma commented
@Dragon-Fish 麻烦看下 dev 分支最新的 commit 有没有解决你的问题。

2021-06-06 09:53 UTC, Dragon-Fish commented
> @Dragon-Fish 麻烦看下 dev 分支最新的 commit 有没有解决你的问题。

本地不方便测试，脑测应该是没问题的

2021-06-12 15:42 UTC, Shigma commented
closed in favor of 8976f250d04f69fb835fc93ca9bebf2e5b8e8d8a

2021-06-12 15:42 UTC, closed without merging