feat: support query expression and regex
koishijs/koishi pull request #305
Opened 2021-07-18 13:29 UTC by NWYLZW

支持 expression

暂时只是在 test utils 中的 mock database 实现了该功能
如果这个语法可以，我会接着这个 pr 将 mysql 与 mongo 实现一遍

2021-07-19 13:37 UTC, NWYLZW commented
---
theme: bricks
background: https://source.unsplash.com/collection/94734566/1920x1080
class: 'text-center'
highlighter: shiki
info: support query expression and regex
---

# koishi orm

有关 koishi orm 对表达式与正则的支持
---

# 原 koishi orm 缺陷

原 koishi orm 虽然也有跨平台的功能，但是对于更复杂的搜索并不是支持的很好。

在这个需求上我对 koishi orm 的功能进行了一些扩充。

* 支持正则表达式
  * mysql 与 mongo 都支持正则，所以实现起来比较简单
* 支持计算表达式
  * mysql 需要转化为对应的计算表达式
  * mongo 与我的设计是相同的所以是直接兼容

---

# 实现效果

定义了一个如下的表结构（从单测中挪出来的）

```ts
declare module 'koishi-core' {
  interface Tables {
    foo: FooData
  }
}

interface FooData {
  id?: number
  bar: string
}

Tables.extend('foo')
```

---

# 使用方法

```ts
await expect(db.createFoo({ bar: 'awesome foo' }))
  .eventually.to.have.shape({ id: 1 })
await expect(db.createFoo({ bar: 'awesome bar' }))
  .eventually.to.have.shape({ id: 2 })
await expect(db.createFoo({ bar: 'awesome foo bar' }))
  .eventually.to.have.shape({ id: 3 })

// 获取被正则 /^.*foo$/ 匹配到数据
await expect(db.get('foo', {
  bar: /^.*foo$/,
})).eventually.to
  .have.nested.property('[0].bar')
  .equal('awesome foo')

// 获取 id 大于 1 的 foo
await expect(db.get('foo', {
  id: { $gt: 1 },
})).eventually.to
  .have.nested.property('[0].bar')
  .equal('awesome bar')
```

---

# 我还未考虑的问题

由于我目前的需求是对计算表达式与正则表达式的需求，所以我想到了条件语句、嵌套查询、以及外键绑定

2021-07-19 16:27 UTC, Shigma commented
或许可以同时支持 `/foo/` 和 `{ $regex: /foo/ }`，以及已经实现的 `[]` 也可以应用到 `{ $in: [] }`。

2021-07-20 09:41 UTC, NWYLZW commented
> 或许可以同时支持 `/foo/` 和 `{ $regex: /foo/ }`，以及已经实现的 `[]` 也可以应用到 `{ $in: [] }`。

前面是同时支持了，后面的这个语法还没有加

我觉得后面的语法类似于 $or，mongo 里面 $or 的语法是这样的

```ts
db.query({
  id: { $or: [{ $eq: 1 }, { $eq: 2 }] }
})
```

我觉得 mongo 的这个语法比较可控一点，也没有引入新的学习成本

2021-07-20 09:56 UTC, Shigma commented
1. `$or` 也建议加上。
2. mongo 官方支持 `$in`，且 `$in` 与 `$or` 实现的性能差距巨大，不建议在可以 `$in` 的场景使用 `$or`。

2021-07-20 09:56 UTC, Shigma commented
https://docs.mongodb.com/manual/reference/operator/query/#comparison

2021-07-20 12:34 UTC, NWYLZW commented
> 1. `$or` 也建议加上。
> 2. mongo 官方支持 `$in`，且 `$in` 与 `$or` 实现的性能差距巨大，不建议在可以 `$in` 的场景使用 `$or`。

均已实现

2021-07-21 13:58 UTC, NWYLZW commented
已支持 mysql，待合并

2021-07-21 19:05 UTC, Shigma requested changes
先提这些，还有些地方没看清之后再看

2021-07-21 19:05 UTC, Shigma commented on packages/koishi-test-utils/src/memory.ts
> +    app.database.memory.$store[name] = []
这里的改动可以，但是不建议修改 Tables.extend，你可以修改 $table 函数。

2021-07-21 19:05 UTC, Shigma commented on packages/koishi-test-utils/tests/memory.spec.ts
> +      db.memory.$store.foo = []
既然有了上面的改动，这行就不需要了

2021-07-21 19:05 UTC, Shigma commented on packages/koishi-test-utils/tests/memory.spec.ts
> +      })).eventually.length(2)
英语语法 eventually to have length，改了就与与其他地方统一，你可以不改 23333

2021-07-21 19:05 UTC, Shigma commented on packages/plugin-mysql/tests/database.spec.ts
> +      expect(createFilter('foo', [1, 2]))
to equal

2021-07-21 19:05 UTC, Shigma commented on packages/plugin-mysql/tests/database.spec.ts
> +      expect(createFilter('foo', [1, 2]))
虽然这个文件跑不到就是了

2021-07-22 03:43 UTC, NWYLZW commented on packages/koishi-test-utils/tests/memory.spec.ts
> +      db.memory.$store.foo = []
忘了，回头删
（自己写了啥都忘记的屑

2021-07-22 05:58 UTC, NWYLZW commented on packages/koishi-core/src/database.ts
> +  type QueryItem<T> = T extends string
非数字支持正则会不会不太好
我先注释这部分，用宽校验

2021-07-22 06:03 UTC, NWYLZW commented on packages/koishi-core/src/database.ts
> +  type QueryMap<O> = {
我这里的意思确实是支持 $or 进行多级嵌套
mongo 允许，详情参考 [此处](https://docs.mongodb.com/manual/reference/operator/query/and/#op._S_and)
mock database、mysql 已经实现，mongo 不需要改动（询问了一下 undefined

2021-07-22 06:07 UTC, NWYLZW commented on packages/koishi-core/src/index.ts
> +    body?: any
我。。。这里不加这个符号，dtsc 指令跑不过去
也不是很弄得懂发生了什么

2021-07-22 06:46 UTC, NWYLZW commented on packages/koishi-test-utils/src/memory.ts
> +            return Object.entries({
一倒是考虑到了
主要是觉得 memory database 目前只是测试用，对性能要求不高，所以就像我那样子写了
我先改成 callback 的形式

2021-07-25 11:27 UTC, Shigma approved these changes

2021-07-25 12:12 UTC, merged