Add Config `delay` in `plugin-rss`
koishijs/koishi pull request #311
Opened 2021-07-27 09:07 UTC by Afanyiyu

Add Config `delay` in `plugin-rss`, passing to `bot.broadcast`

2021-07-27 10:05 UTC, Shigma requested changes

2021-07-27 10:05 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
这里还是应该用 forEach
同一个 bot 发送消息可以有延迟，但是不同 bot 应该同时开始发送序列

2021-07-27 10:06 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
然后其实 ctx.broadcast 跟 bot.broadcast 的一参数的语义是不一样的，也不能替换

2021-07-27 10:07 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
不如说建议这个需求直接通过配置 appOptions 就可以解决

2021-07-27 10:09 UTC, Afanyiyu commented
K 改了

2021-07-27 10:11 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
> 然后其实 ctx.broadcast 跟 bot.broadcast 的一参数的语义是不一样的，也不能替换

诶  还有这样的事

2021-07-27 10:12 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
> 不如说建议这个需求直接通过配置 appOptions 就可以解决

但是这里会有只想让 `rss` 吐得慢一点的需求啊

2021-07-27 10:12 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
说白了其实还是 `rss` 吐得太快了导致的封号

2021-07-27 13:49 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
如果只有 rss 吐的快，那你修改配置也能解决

如果不只有 rss 吐的快，其他地方也会导致封号，所以其实是一样的

2021-07-27 13:50 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
https://koishi.js.org/guide/message.html#%E5%8F%91%E9%80%81%E5%B9%BF%E6%92%AD%E6%B6%88%E6%81%AF

2021-07-27 13:56 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
> 如果只有 rss 吐的快，那你修改配置也能解决
> 
> 如果不只有 rss 吐的快，其他地方也会导致封号，所以其实是一样的

o 好像非常有道理

2021-07-27 13:57 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
顺便问下，这个配置项的默认值是多少 文档里没找见

2021-07-28 15:47 UTC, Shigma commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
@Afanyiyu 0.5 秒，之后会更新文档

2021-07-28 15:49 UTC, Afanyiyu commented on packages/plugin-rss/src/index.ts
> +      for (const bot of ctx.bots) await bot.broadcast([...feedMap[source]], message, config.delay)
> @Afanyiyu 0.5 秒，之后会更新文档

好  那没别的问题了的话这个 PR 就可以关了

2021-07-28 17:43 UTC, closed without merging