feat(puppeteer): support to configure styles while rendering fragment segments
koishijs/koishi pull request #318
Opened 2021-07-29 18:12 UTC by Anillc

… segments

2021-07-30 17:19 UTC, Shigma commented on packages/plugin-puppeteer/package.json
> +    "koishi-utils": "^4.2.3"
好像目前的插件都不加这个 peerDep，你可以直接从 koishi-core 引入 hyphenate

2021-07-30 17:19 UTC, Shigma commented on packages/plugin-puppeteer/src/index.ts
> +  bodyStyles?: Record<string, string>
建议 style 用单数，然后这里 bodyStyle 好像也有点不明确，我们先讨论下有没有其他合适的命名

2021-07-30 17:19 UTC, Shigma commented on packages/plugin-puppeteer/src/index.ts
> +    padding: '0.25rem 0.375rem',
如果你觉得 padding 是不必要的，可以删掉，当然保留也可以 :)

2021-07-30 17:19 UTC, Shigma commented on packages/plugin-puppeteer/src/index.ts
> +                .reduce((acc, entry) => acc += `${hyphenate(entry[0])}: ${entry[1]};`, '')
我的建议是提到外部，然后改用 map+join，看起来稍微清楚一点。

```js
const style = Object
  .entries()
  .map()
  .join()
```

2021-07-30 17:50 UTC, Anillc commented on packages/plugin-puppeteer/src/index.ts
> +    padding: '0.25rem 0.375rem',
padding 只是我自己在使用的时候遇到的问题，预留一个边距对大多数情况下应该都是好的

2021-08-08 08:10 UTC, Shigma requested changes

2021-08-08 08:10 UTC, Shigma commented on packages/plugin-puppeteer/src/index.ts
> +            .map(([key, value]) => `${hyphenate(key)}: ${value};`)
其实这里可以不要那个分号，然后下面用 `join('; ')` 看起来稍好一些

2021-08-08 08:10 UTC, Shigma commented on packages/plugin-puppeteer/src/index.ts
> +  bodyStyle?: Record<string, string>
jsxContainerStyle 怎么样呢

2021-08-08 13:30 UTC, Anillc commented on packages/plugin-puppeteer/src/index.ts
> +            .map(([key, value]) => `${hyphenate(key)}: ${value};`)
我的习惯是最后加上分号，我会修改一下

2021-08-08 13:31 UTC, Anillc commented on packages/plugin-puppeteer/src/index.ts
> +  bodyStyle?: Record<string, string>
Container 也许不是很合适，不过只要在文档里写好叫什么都没问题（

2021-08-08 13:48 UTC, merged