fix(test-utils): orm expr query behavior for `$eq`, `$ne` and so on
koishijs/koishi pull request #343
Opened 2021-08-14 15:29 UTC by NWYLZW

#338

2021-08-14 15:32 UTC, NWYLZW commented
应该是因为 mongo 和 mysql 挂 unit test

2021-08-14 15:36 UTC, Shigma requested changes

2021-08-14 15:36 UTC, Shigma commented on packages/koishi-test-utils/tests/memory.spec.ts
> +  datetime?: Date
直接叫 date 比较好？

2021-08-14 15:36 UTC, Shigma commented on packages/koishi-test-utils/tests/memory.spec.ts
> +    it('should check in addition to basic types.', async () => {
should convert date to primitives when doing comparisons

2021-08-14 15:36 UTC, Shigma commented on packages/koishi-test-utils/src/memory.ts
> +  if (!data) return false
这是为啥

2021-08-14 15:37 UTC, NWYLZW commented on packages/koishi-test-utils/src/memory.ts
> +  if (!data) return false
因为数据不存在的时候应该是匹配失败

2021-08-14 15:38 UTC, NWYLZW commented on packages/koishi-test-utils/tests/memory.spec.ts
> +    it('should check in addition to basic types.', async () => {
我开始本来以为可以支持 json，然后就这么写
后面发现只能支持 date，我待会儿改一下

2021-08-14 15:45 UTC, Shigma commented on packages/koishi-test-utils/src/memory.ts
> +  if (!data) return false
这里处理不正确，如果是 0 或者其他 falsy 就会造成非预期的结果。

应该在 executeQuery 最下面调用本函数前面加一行：

```ts
if (!(key in data)) return false
```

2021-08-15 03:56 UTC, Shigma approved these changes

2021-08-15 03:56 UTC, merged