new adapter for qq guild
koishijs/koishi pull request #421
Opened 2021-12-05 07:41 UTC by NWYLZW

2021-12-05 11:40 UTC, Shigma requested changes

2021-12-05 11:40 UTC, Shigma commented on plugins/adapter/qqguild/src/ws.ts
> +    endpoint: Schema.string()
这里 endpoint 不需要了，request 里面有

2021-12-05 11:40 UTC, Shigma commented on plugins/adapter/qqguild/README.md
> +# QQ 频道适配器
建议写到 docs 里面而不是这里

2021-12-05 12:52 UTC, NWYLZW commented on plugins/adapter/qqguild/src/ws.ts
> +    endpoint: Schema.string()
request 里面的那个默认值可以改吗？
可以的话，咋改

2021-12-12 19:35 UTC, Shigma approved these changes

2021-12-12 19:42 UTC, merged