fix(github): ctx
koishijs/koishi pull request #450
Opened 2022-01-06 11:51 UTC by XxLittleCxX

2022-01-06 12:06 UTC, Shigma requested changes

2022-01-06 12:06 UTC, Shigma commented on plugins/github/src/server.ts
> +    return this.http.post<OAuth>('https://github.com/login/oauth/access_token', {}, {
这边不对，不是最新代码

2022-01-06 12:06 UTC, Shigma commented on plugins/github/src/index.ts
> +    if (!token || Array.isArray(token)) return koaCtx.status = 400
草，变量名有点丑，直接 _ctx 吧

2022-01-06 12:07 UTC, XxLittleCxX commented on plugins/github/src/server.ts
> +    return this.http.post<OAuth>('https://github.com/login/oauth/access_token', {}, {
刚从 develop 拉的还不行吗（

2022-01-06 12:16 UTC, XxLittleCxX commented
等等merge 下面还有同样的问题

2022-01-08 18:17 UTC, Shigma approved these changes

2022-01-08 18:17 UTC, merged