[WIP] docs: add crowdin guide
koishijs/koishi pull request #579
Opened 2022-03-18 03:49 UTC by MaikoTan

2022-03-18 13:24 UTC, MaikoTan commented
@Shigma Still don't know how much should I cover.

2022-03-27 07:08 UTC, Shigma requested changes

2022-03-27 07:08 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +除了 Crowdin，还有很多其他平台也提供类似的功能，有一些甚至是完全免费的，如：[Transifex](https://www.transifex.com)、[Memsource](https://www.memsource.com/)、[Lokalise](https://lokalise.com/)、[POEditor](https://poeditor.com/) 等等。你也可以尝试搜
冒号与等等只保留一个。这里建议直接换成列表。

Translation Management System 不建议用 code。

2022-03-27 07:08 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +导航至 Crowdin 的内容（Content）界面，你可以点击上传文件（Upload Files）按钮上传**源语言**文件。
```diff
- 圆括号均使用半角，并且两侧留空格（外侧有其他标点符号的情况除外）。
+ 圆括号均使用半角，并且两侧留空格 (外侧有其他标点符号的情况除外)。
```

2022-03-27 07:08 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +Crowdin 还提供了一个 CLI 工具，可以通过命令行管理本地和远程的本地化资源文件。如果你使用的系统是 MacOS，则你可以通过运行下面两行代码方便地安装 Crowdin CLI。*其他平台的安装方式可以查看[Crowdin 的文档](https://support.crowdin.com/cli-tool/#installation)*
不建议使用斜体。中文字符显示为斜体的可读性极差。可以考虑不强调说明。

Crowdin 左侧空格。右侧补一个句号。

2022-03-27 07:08 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +
多了一个空行。

2022-03-27 07:08 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +# 使用 Crowdin 管理 i18n 资源
我有一点担心这个标题太长了左侧栏显示不下……要不要改成接入 Crowdin 之类？

2022-03-27 11:18 UTC, MaikoTan commented on docs/guide/i18n/crowdin.md
> +Crowdin 还提供了一个 CLI 工具，可以通过命令行管理本地和远程的本地化资源文件。如果你使用的系统是 MacOS，则你可以通过运行下面两行代码方便地安装 Crowdin CLI。*其他平台的安装方式可以查看[Crowdin 的文档](https://support.crowdin.com/cli-tool/#installation)*
got it.

此处我考虑直接写 `npm i -g @crowdin/cli` 的安装法即可，不写 MacOS 什么的了

2022-03-28 00:54 UTC, MaikoTan commented on docs/guide/i18n/crowdin.md
> +# 使用 Crowdin 管理 i18n 资源
我觉得可以，不过需要在页面开头详细介绍一下这是个什么东西，以及用户是否真的需要它。
这毕竟是个商业公司，我是比较反对滥用的，如果不需要那就不要用。

2022-04-10 09:16 UTC, Shigma requested changes

2022-04-10 09:16 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +      dress: {name}今天穿了{color}色的裙子
这一行要加 '' 转义，因为 yaml 会将 `{` 理解成对象的开始。

2022-04-10 09:16 UTC, Shigma commented on docs/guide/i18n/crowdin.md
> +在运行 Crowdin 的 CLI 工具之前，你需要确保当前项目的根目录下存在名为 `crowdin.yml` 的配置文件，你可以运行 `crowdin init` 创建一个基础配置文件，修改其中的条目以适应你的项目。详细的介绍可以看[Crowdin 的文档](https://support.crowdin.com/configuration-file/)。
链接前面缺一个空格。

2022-04-10 14:44 UTC, MaikoTan commented on docs/guide/i18n/crowdin.md
> +在运行 Crowdin 的 CLI 工具之前，你需要确保当前项目的根目录下存在名为 `crowdin.yml` 的配置文件，你可以运行 `crowdin init` 创建一个基础配置文件，修改其中的条目以适应你的项目。详细的介绍可以看[Crowdin 的文档](https://support.crowdin.com/configuration-file/)。
```suggestion
在运行 Crowdin 的 CLI 工具之前，你需要确保当前项目的根目录下存在名为 `crowdin.yml` 的配置文件，你可以运行 `crowdin init` 创建一个基础配置文件，修改其中的条目以适应你的项目。详细的介绍可以看 [Crowdin 的文档](https://support.crowdin.com/configuration-file/)。
```

2022-04-10 14:44 UTC, MaikoTan commented on docs/guide/i18n/crowdin.md
> +      dress: {name}今天穿了{color}色的裙子
```suggestion
      dress: '{name}今天穿了{color}色的裙子'
```

2022-04-11 03:07 UTC, Shigma approved these changes

2022-04-11 03:08 UTC, merged