i18n: experimental japanese localisation in locale
koishijs/koishi pull request #643
Opened 2022-04-28 08:18 UTC by MaikoTan

2022-04-28 12:31 UTC, ilharp requested changes
不会 JP 语，轻喷

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  or: や
话说 `and` 和 `or` 是在什么时候会用到啊

另外

```yml
day: 日
hour: 時間
minute: 分
second: 秒
```

是不是少了

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  invalid-option: 無効なオプション「{0}」、{1}
不一致的地方有点多啊  可以先把术语统一下？

概念|表述
-|-
argument|パラメータ
option|オプション

这是我的建议（总感觉有点 zh-MS

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
`「help」を送信して使い方を確認してください。`

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  hint: 「{0}」で続行しますか？
这里其实体现出来「hint」的含义？虽然其实没必要，和下面 `help-suffix` 连起来之后能够正确表意了

但为什么是 `続行`

`「{0}」で実行しますか？`

`「{0}」のことですか？`

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
`command-suffix` `help-suffix` 不一致

`この提案を実行するには、空白行または句点を送信します。`

`句点` 还是 `ピリオド`（period）？

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +      help: ヘルプメッセージを表示
`このメッセージを表示`

2022-04-28 12:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（括弧には最低権限が表示されています）：'
与 L40 不一致

`追加の必要な権限は括弧にで表示されています`

2022-04-28 12:39 UTC, MaikoTan commented
我翻譯時大概喝了假酒（）

2022-04-28 12:42 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
用送信會不會有點奇怪，畢竟這裡是調用指令而不是發送信息？

2022-04-28 12:42 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  invalid-option: 無効なオプション「{0}」、{1}
好👌（

2022-04-28 12:43 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  hint: 「{0}」で続行しますか？
哦，我一開始理解錯了。

你是對的，我覺得1比較好。

2022-04-28 12:43 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
呃，這個得問下夢夢（）

2022-04-28 12:45 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
诶诶  我不清楚这句具体是在什么地方会用到诶

en 里是 `Type help to see usage.`    这里不是发送的意思吗

2022-04-28 12:45 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（括弧には最低権限が表示されています）：'
為什麼是追加？

2022-04-28 12:51 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
這裡當然是看中文啦

`输入帮助以查看用法。`
好像送信也沒錯（

2022-04-28 13:11 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（括弧には最低権限が表示されています）：'
`追加の必要な権限`  追加需要的权限

en 是 `additional authority requirement`

不过这个好像就跟 L40 相同也没问题

2022-04-28 13:12 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
可以问问梦梦？我主要是不清楚这个是显示在哪里的

2022-04-28 13:14 UTC, ilharp approved these changes
……LGTM？不过我本身也不太懂就是了（

2022-04-28 13:15 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（括弧には最低権限が表示されています）：'
這裡的意思是，執行選項要求的權限等級會比上述的指令等級更高的時候，就會顯示這句話。

2022-04-28 13:20 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（括弧には最低権限が表示されています）：'
了解了

（对哦，我为什么不看中文（（

2022-04-28 13:42 UTC, MaikoTan commented
> ……LGTM？不过我本身也不太懂就是了（
> 
> 

其實還有不一致的地方，比如"輸入"要翻譯成"入力"還是"送信"？

2022-04-28 13:44 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
應該這樣寫更自然一些吧
"提案したコマンドを実行するには"

2022-04-28 13:44 UTC, ilharp commented
> > ……LGTM？不过我本身也不太懂就是了（
> 
> 其實還有不一致的地方，比如"輸入"要翻譯成"入力"還是"送信"？

其实可以问问梦梦？我的话是觉得中文现在用的「输入」就不怎么好……中文也应该用「发送」比较好

但又根据小改小动原则  已经存在很长时间的东西就不应该改了  所以就（

2022-04-28 13:46 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
这一句是紧挨着 `hint` 的吧   所以我是觉得这里按照最小说明来就行  怎么省怎么来（

2022-04-28 13:49 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
![IMG_20220428_214822.jpg](https://user-images.githubusercontent.com/19927330/165767188-5c680fc8-7fc2-4ad4-a09f-a2b042d72b81.jpg)

2022-04-28 13:51 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  help-suffix: 空行または句点でこのコマンドを実行します。
唔呣……

2022-04-28 13:52 UTC, Shigma commented
中文的话感觉发送确实稍好，按发送的逻辑写吧

2022-04-28 13:57 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  insufficient-arguments: パラメータが不足してます、「help」コマンドで使い方を検索してください。
```suggestion
  insufficient-arguments: パラメータが不足しています、「help」コマンドで使い方を確認してください。
```

2022-04-28 13:57 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  redunant-arguments: パラメータ数が多すぎます、「help」コマンドで使い方を検索してください。
```suggestion
  redunant-arguments: パラメータ数が多すぎます、「help」コマンドで使い方を確認してください。
```

2022-04-28 13:57 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  unknown-option: 未知なオプション「{0}」、「help」コマンドで使い方を検索してください。
```suggestion
  unknown-option: 未知なオプション「{0}」、「help」コマンドで使い方を確認してください。
```

2022-04-28 13:57 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  hint: 「{0}」で実行しますか？
```suggestion
  hint: 「{0}」を実行したいですか？
```

2022-04-28 13:57 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  command-suffix: 句点でこのコマンドを実行します。
```suggestion
  command-suffix: 句点を入力してコマンドを実行します。
```

2022-04-28 14:06 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  check-syntax: 「help」コマンドで使い方を検索してください。
```suggestion
  check-syntax: 「help」を送信して使い方を検索してください。
```

2022-04-28 14:07 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  hint: 「{0}」で実行しますか？
@ilharp Is it good?

2022-04-28 14:08 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +      global-epilog: 「help <command>」を入力するとコマンドの使い方を表示します。
```suggestion
      global-epilog: 「help <command>」を送信してコマンドの使い方を表示します。
```

2022-04-28 14:09 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（必要な権限は括弧にで表示されています）：'
@ilharp `必要な権限` vs `最低に必要な権限`

2022-04-28 14:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  hint: 「{0}」で実行しますか？
LGTM？

2022-04-28 14:31 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +      available-options-with-authority: '利用可能なオプション（必要な権限は括弧にで表示されています）：'
`必要な権限`

2022-04-28 15:06 UTC, MaikoTan commented
I think good to merge ?

2022-04-28 15:23 UTC, ilharp approved these changes
LGTM（二度

2022-04-29 10:29 UTC, ilharp requested changes

2022-04-29 10:40 UTC, MaikoTan commented on packages/core/src/locales/ja.yml
> +  command-suffix: 句点を送信してコマンドを実行します。
这里中文和英文也不一致……
中文：发送空行或句号
英文：发送句号

2022-04-29 10:41 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  command-suffix: 句点を送信してコマンドを実行します。
我倾向于这里因为也应该有空行

问问梦梦？

2022-04-29 11:03 UTC, ilharp commented on packages/core/src/locales/ja.yml
> +  command-suffix: 句点を送信してコマンドを実行します。
那 L34 也改成句点？

2022-04-29 20:39 UTC, Shigma commented on packages/core/src/locales/ja.yml
> +  command-suffix: 句点を送信してコマンドを実行します。
同意，甚至你可以顺手改一下中文的

2022-04-29 20:41 UTC, Shigma commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
别的地方都是片假，就这里写英文会不会奇怪？

2022-04-29 23:15 UTC, MaikoTan commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
做了一下小調查：
ボット：通常是指非法的自動程序，如木馬病毒，或是遊戲外掛等等。
BOT：同上，但含義會弱一些，某些場合可以指代聊天機器人（チャットボット）
ロボット：更多的指代有實體的機器人，如工業機械手等等。
チャットボット/チャットBOT：沒看出來區別，應該是最符合描述的。

此外，我在法語中也是寫 robot，不清楚要不要改？

2022-04-29 23:21 UTC, ilharp commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
我个人比较建议使用 `Bot` 或 `BOT`。这是 Bot 的专有名词。

`ボット`、`ロボット` 和 `チャットボット` 均在字面上含义相同，但这么用的人少得多。我所在的所有 JP 服务器里给 Bot 的分组都是 `BOT`。虽然 Discord 官方给定的标签是 `ボット`，但很少看到人这么称呼 Bot

---

![image](https://user-images.githubusercontent.com/20179549/166079958-eb79a97d-5a68-4fb7-92d9-5c7865a0c46b.png)

草

2022-04-30 01:55 UTC, Shigma commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
你们觉得没问题就好……我不太清楚有没有直接写英文字母的实践。如果是书面语的话其实チャットボット我也能接受。

2022-04-30 02:30 UTC, MaikoTan commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
按微軟做例子的話，早期確實存在很多强行片假名的情況，比如説 IE 翻譯成 インターネットエクスプローラー。
~~所以就會出現類似於，マイクロソフト社が開発したウインドウズ オペレーティングシステムに付属の標準ブラウザ インターネットエクスプローラーについて……~~
但是後來這種翻譯越來越少了，幾乎都用英語及其縮寫，所以我覺得 IT 相關的應該都可以這樣處理（？

2022-04-30 11:56 UTC, ilharp requested changes

2022-04-30 11:56 UTC, ilharp commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
话说这里是否需要盘古？在 BOT 后空格

2022-04-30 12:04 UTC, Shigma commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
我的问题是，日语是否需要遵循盘古？

2022-04-30 12:05 UTC, ilharp commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
我认为是需要的  很有必要

盘古本身就是为分隔全角和半角字符的  和语言无关

2022-04-30 12:13 UTC, MaikoTan commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
其实 fr 那边我也没特别遵循规则，比如说法语的引号是这个 « »…

2022-04-30 12:15 UTC, MaikoTan commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
https://docs.microsoft.com/ja-JP/adaptive-cards/

比如 ja-MS 是有加空格的，我们也加吧？

2022-04-30 12:34 UTC, Shigma commented on packages/cli/src/locales/ja.yml
> +    description: BOTをシャットダウンする。
那加

2022-04-30 12:36 UTC, MaikoTan commented
Good to merge!

2022-04-30 12:37 UTC, ilharp approved these changes
LGTM

2022-04-30 18:31 UTC, Shigma approved these changes

2022-04-30 18:31 UTC, merged