feat(manager): set registry manually
koishijs/koishi pull request #657
Opened 2022-05-02 16:36 UTC by H4M5TER

solve #654

2022-05-02 16:54 UTC, Shigma requested changes

2022-05-02 16:54 UTC, Shigma commented on plugins/frontend/manager/src/index.ts
> +export function apply(ctx: Context, config: Config = { registry: '' }) {
下面已经有 default 了，不需要这个默认值。

2022-05-02 16:54 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
下面 prepare 中只会用到一次，不是一个有状态量。

2022-05-02 16:54 UTC, Shigma commented on plugins/frontend/manager/src/index.ts
> +export function apply(ctx: Context, config: Config = { registry: '' }) {
其实下面也不需要这个空串，因为你甚至得判空，这是无意义的

2022-05-02 16:55 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('插件市场查询的 registry，需要支持搜索功能').default(''),
ok，

2022-05-02 16:57 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
哦，这里我也想到了，就是看起来 prepare 也只要跑一次，但是我不想太随便改变获取 registry 的位置，就还是把它存了放到了下面。
但是我不知道  config 原来是持久化到 this 了的。

2022-05-02 16:58 UTC, H4M5TER commented on plugins/frontend/manager/src/index.ts
> +export function apply(ctx: Context, config: Config = { registry: '' }) {
我这里在群里说了，是被 eslint 殴打了

2022-05-02 17:00 UTC, Shigma reviewed
然后为了确保安装体验的一致性，你需要给 installer.ts 也添加一个 Config，里面包含相同的 registry 配置项（但是不写 schema），并在有 registry 的时候添加 `--registry` 选项，在没有的时候不添加。

2022-05-02 17:00 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('插件市场查询的 registry，需要支持搜索功能').default(''),
我觉得这里语义明确是“插件市场查询”了，不知道怎么改比较好，帮我想想

2022-05-02 17:00 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('插件市场查询的 registry，需要支持搜索功能').default(''),
“用于插件市场” 的话，感觉，也，差不多啊

2022-05-02 17:02 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('插件市场查询的 registry，需要支持搜索功能').default(''),
不应该强调查询，因为你下载也要用。

2022-05-02 17:07 UTC, H4M5TER commented on plugins/frontend/manager/src/index.ts
> +export function apply(ctx: Context, config: Config = { registry: '' }) {
后面类型写了 ?: 之后前面忘删了

2022-05-02 17:17 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
关于第二种写法，我有点问题：
registry 这里无论如何都是有 schemastery 给的值 '' 的吧，那我这里使用缺省值是否会失效

2022-05-02 17:19 UTC, H4M5TER commented
> 然后为了确保安装体验的一致性，你需要给 installer.ts 也添加一个 Config，里面包含相同的 registry 配置项（但是不写 schema），并在有 registry 的时候添加 `--registry` 选项，在没有的时候不添加。

如果这个 registry 需要在整体使用，我是否应该把它提到 manager 的层面？

2022-05-02 17:24 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
你可以把 registry 缺省值删了，不过这里我还是建议第一种，覆盖的面更广一些，毕竟空串对 registry 无意义

2022-05-02 17:25 UTC, Shigma commented
> 如果这个 registry 需要在整体使用，我是否应该把它提到 manager 的层面？

你提是可以提的但是类型不好写，不如分开。

2022-05-02 17:30 UTC, H4M5TER commented
我没懂现在要怎么拿到 registry，这个 eventListener 是怎么传参的

2022-05-02 17:31 UTC, Shigma commented
跟 eventListener 没关系，你 config.registry 就是

2022-05-02 17:32 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
等等所以，config 真的是已经持久化到 this 了吗？

2022-05-02 17:33 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
constructor 里没写我想不到这是怎么做到的

2022-05-02 17:35 UTC, H4M5TER commented
哦，我知道了，ctx.market.config.registry 是吧，可以

2022-05-02 17:52 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
原来是 糖

2022-05-02 18:54 UTC, Shigma requested changes

2022-05-02 18:54 UTC, Shigma commented on plugins/frontend/manager/src/installer.ts
> +    if (registry !== '') args.push('--registry=' + registry)
直接 registry，不要判空，没意义的

2022-05-02 18:54 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
属性没删

2022-05-02 18:54 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +      this.config.registry = await new Promise<string>((resolve, reject) => {
你不应该修改配置，上面改 let

2022-05-02 18:54 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +      this.config.registry = await new Promise<string>((resolve, reject) => {
配置是可能被写回配置文件的

2022-05-02 18:54 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('用于插件市场搜索和下载的 registry，需要支持搜索功能').default(''),
后半句没必要吧？

2022-05-02 18:57 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('用于插件市场搜索和下载的 registry，需要支持搜索功能').default(''),
确实，反正等报错

2022-05-02 18:58 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +      this.config.registry = await new Promise<string>((resolve, reject) => {
我本来想说这个会配合 installer，然后我想了想，installer 用的就是同一个 agent，没有区别，不需要写

2022-05-02 18:58 UTC, Shigma commented on plugins/frontend/manager/src/market.ts
> +    registry: Schema.string().description('用于插件市场搜索和下载的 registry，需要支持搜索功能').default(''),
还有加上句号。

2022-05-02 18:58 UTC, H4M5TER commented on plugins/frontend/manager/src/installer.ts
> +    if (registry !== '') args.push('--registry=' + registry)
行为会一样吗

2022-05-02 18:59 UTC, H4M5TER commented on plugins/frontend/manager/src/market.ts
> +  private registry: string
这 eslint 怎么不殴打我的

2022-05-02 19:00 UTC, Shigma commented on plugins/frontend/manager/src/installer.ts
> +    if (registry !== '') args.push('--registry=' + registry)
空值和空串对 registry 都是没法用的

2022-05-02 19:01 UTC, Shigma commented on plugins/frontend/manager/src/installer.ts
> +    if (registry !== '') args.push('--registry=' + registry)
程序应该排除疑似错误的分支，过早过严格优化只会增加维护成本

2022-05-02 19:02 UTC, H4M5TER commented on plugins/frontend/manager/src/installer.ts
> +    if (registry !== '') args.push('--registry=' + registry)
这里不会有空值
搜了一下 '' 会转成 false，那没问题

2022-05-02 19:23 UTC, H4M5TER commented
提一嘴，我觉得，如果检查本地 failed 了，我们可以 fallback 到 https://registry.npmjs.org

2022-05-02 19:30 UTC, H4M5TER commented
但是会导致不一致性，但是考虑到一般人本地是能访问 registry 的，我觉得总体可以减少问不合格问题的人

2022-05-02 20:55 UTC, Shigma commented on plugins/frontend/manager/src/installer.ts
> +    const registry = this.ctx['console.market'].config.registry
你似乎可以 this.ctx.console.market

2022-05-03 10:26 UTC, Shigma approved these changes

2022-05-03 10:27 UTC, merged