i18n(core/cli/helper): add traditional chinese
koishijs/koishi pull request #666
Opened 2022-05-05 05:46 UTC by MaikoTan

2022-05-05 06:06 UTC, shigma requested changes

2022-05-05 06:06 UTC, shigma commented on packages/cli/src/worker/daemon.ts
> +    ctx.i18n.define('zht', require('../locales/zht'))
zh-tw 吧，未来做回退用这种格式比较方便

2022-05-05 06:55 UTC, MaikoTan commented on packages/cli/src/worker/daemon.ts
> +    ctx.i18n.define('zht', require('../locales/zht'))
Done!

2022-05-05 07:02 UTC, shigma commented on packages/cli/src/worker/daemon.ts
> +    ctx.i18n.define('zht', require('../locales/zht'))
文件名没改（

2022-05-08 12:43 UTC, shigma approved these changes

2022-05-08 15:53 UTC, undefined-moe requested changes

2022-05-08 15:53 UTC, undefined-moe commented on packages/core/src/locales/zh-tw.yml
> +  insufficient-arguments: 參數個數不足，輸入「help」查看用法。
檢視

2022-05-08 15:53 UTC, undefined-moe commented on packages/core/src/locales/zh-tw.yml
> +      authority: 顯示權限設置
設定

2022-05-08 15:55 UTC, undefined-moe commented on packages/helpers/src/locales/zh-tw.yml
> +  channel-not-found: 找不到指定的頻道。
指定的頻道不存在。

2022-05-08 16:10 UTC, KusakabeShi commented on packages/cli/src/locales/zh-tw.yml
> +      restart: 重啓
咱感覺用「重新啟動」必較正式一點

2022-05-08 16:10 UTC, KusakabeShi commented on packages/core/src/locales/zh-tw.yml
> +  low-authority: 沒有足夠的權限。
權限不足

2022-05-08 16:10 UTC, KusakabeShi commented on packages/core/src/locales/zh-tw.yml
> +  invalid-user: 請指定有效用戶。
user叫「使用者」比較常見

2022-05-08 16:10 UTC, KusakabeShi commented on packages/helpers/src/locales/zh-tw.yml
> +  user-updated: 已改變用戶數據。
使用者資料已更新

2022-05-08 16:10 UTC, KusakabeShi commented on packages/helpers/src/locales/zh-tw.yml
> +  user-unchanged: 沒有改變用戶數據。
使用者資料未更新

2022-05-08 16:10 UTC, KusakabeShi commented on packages/helpers/src/locales/zh-tw.yml
> +  channel-updated: 已改變頻道數據。
頻道已更新

2022-05-08 16:16 UTC, MaikoTan commented on packages/core/src/locales/zh-tw.yml
> +  invalid-user: 請指定有效用戶。
這裡其實是指「當前的頻道裡的其他 user」，所以我覺得用「用戶」可能更貼切一些的。

2022-05-08 19:46 UTC, KusakabeShi commented on packages/core/src/locales/zh-tw.yml
> +  invalid-user: 請指定有效用戶。
也是可以

2022-05-09 17:21 UTC, merged