fix: fix attachments is not resolve and support resolve string intents
koishijs/koishi pull request #672
Opened 2022-05-08 09:36 UTC by NWYLZW

#622

2022-05-08 09:43 UTC, shigma requested changes

2022-05-08 09:43 UTC, shigma commented on plugins/adapter/qqguild/src/utils.ts
> +  intents: number | Intents | Intents[]
不建议改，控制台没法用

2022-05-08 09:43 UTC, shigma commented on plugins/adapter/qqguild/src/utils.ts
> +  intents: number | Intents | Intents[]
以后会支持 bitset

2022-05-08 09:43 UTC, shigma commented on plugins/adapter/qqguild/src/ws.ts
> +    ?? ''
不如 (content ?? '').replace，这样写编译出来特别长

2022-05-08 09:43 UTC, shigma commented on plugins/adapter/qqguild/package.json
> +  "version": "2.0.0",
why

2022-05-08 09:47 UTC, NWYLZW commented on plugins/adapter/qqguild/package.json
> +  "version": "2.0.0",
因为 sdk 升级了个版本
官方有几个 intent 的名字换了
算是一个大的 breaking change 吧

2022-05-08 09:49 UTC, NWYLZW commented on plugins/adapter/qqguild/package.json
> +  "version": "2.0.0",
上个版本有个 intent 叫 AT_MESSAGES ，现在叫 PUBLIC_GUILD_MESSAGES

2022-05-08 09:55 UTC, NWYLZW commented on plugins/adapter/qqguild/src/utils.ts
> +  intents: number | Intents | Intents[]
控制台还不支持 shema.union 吗

2022-05-08 09:56 UTC, NWYLZW commented on plugins/adapter/qqguild/src/utils.ts
> +  intents: number | Intents | Intents[]
支持这个的原因是因为好几次有人问我 intent 怎么填
我觉得支持 string 数组对用户可能会体验好一点

2022-05-08 09:58 UTC, NWYLZW commented on plugins/adapter/qqguild/src/utils.ts
> +  intents: number | Intents | Intents[]
我可以让暴露给控制台的 schema config 只能使用 number 类型
这样子控制台也能直接用，用户用配置文件的时候也能支持更方便的配置

2022-05-08 15:48 UTC, shigma requested changes

2022-05-08 15:48 UTC, shigma commented on plugins/adapter/qqguild/src/utils.ts
> +    intents: Schema.number(),
description 补一下

2022-05-08 15:48 UTC, shigma commented on plugins/adapter/qqguild/src/ws.ts
> +      (content, attachment) => content + segment.image(attachment.url), session.content,
这就别换行了老短了（

2022-05-08 15:48 UTC, shigma commented on plugins/adapter/qqguild/src/ws.ts
> +    Array.isArray(intents) || (intents = [intents])
```ts
import { makeArray } from 'koishi'
```

2022-05-08 15:48 UTC, shigma commented on plugins/adapter/qqguild/src/ws.ts
> +    Array.isArray(intents) || (intents = [intents])
其实也不太建议搞 string，直接 array 更合理，有永远只需要传一个 intent 的人吗？

2022-05-08 15:48 UTC, shigma commented on plugins/adapter/qqguild/src/utils.ts
> +    intents: Schema.number(),
有没有默认值？

2022-05-08 16:01 UTC, NWYLZW commented on plugins/adapter/qqguild/src/utils.ts
> +    intents: Schema.number(),
忘了，不过这个没有默认值，如果没填会报错

2022-05-08 16:02 UTC, NWYLZW commented on plugins/adapter/qqguild/src/ws.ts
> +    Array.isArray(intents) || (intents = [intents])
也是，合理
那就支持单个 string 了叭

2022-05-08 16:11 UTC, shigma commented on plugins/adapter/qqguild/src/utils.ts
> +    intents: Schema.number(),
我是说，你能不能提供默认值呢？

2022-05-09 02:44 UTC, NWYLZW commented on plugins/adapter/qqguild/src/utils.ts
> +    intents: Schema.number(),
那我加一个默认接受公域消息的 intent 吧

2022-05-09 17:19 UTC, shigma requested changes

2022-05-09 17:19 UTC, shigma commented on plugins/adapter/qqguild/src/ws.ts
> +    }
你可以直接在 schemastery 中使用 `.required()` 而不是这里。

2022-05-10 06:11 UTC, NWYLZW commented on plugins/adapter/qqguild/src/ws.ts
> +    }
ok

2022-05-10 07:07 UTC, shigma approved these changes

2022-05-10 07:09 UTC, merged