Add milestoned issue backlogging
koishijs/koishi pull request #674
Opened 2022-05-08 21:13 UTC by H4M5TER

已经跑通了，配一下 secrets.BACKLOG_PAT

2022-05-09 08:28 UTC, shigma reviewed
改 ts 放 build 目录

2022-05-09 12:13 UTC, H4M5TER commented
> 加一行 `if: ${{ github.repository == 'koishijs/koishi' }}`
> 
> 毕竟它在 fork 上运行毫无意义

fork 没有 milestone 和 issue 的话不会触发这个的吧，但是可以，因为我代码里硬编码 shigma 了

2022-05-09 12:15 UTC, H4M5TER commented
> 改 ts 放 build 目录

介绍一下 build 目录是怎么工作的，你希望 ci 在哪里拿到编译好的 backlog.js，以及我要怎么让它编译到那里去

2022-05-09 12:47 UTC, MaikoTan commented
> > 改 ts 放 build 目录
> 
> 
> 
> 介绍一下 build 目录是怎么工作的，你希望 ci 在哪里拿到编译好的 backlog.js，以及我要怎么让它编译到那里去

`node -r ./build/register ./build/backlog.ts` 可以直接運行 ts 文件（記得先 yarn install）

2022-05-09 13:06 UTC, H4M5TER commented
这是 CI 标准流程吗，需不需要指定一下要装的包（esbuild 和什么），如果全部都装的话，我就直接在 setup-node 里 cache: yarn 了，有一个问题是 install 的速度很大跟 ci 服务器有没有缓存有关系，（之前已经遇到但是忘记提了）导致如果短时间触发两次 action 的话，有可能第二个装完包跑完了第一个才开始跑，导致一点问题。（可能多装一点包还能拉平这个装包时间（（

2022-05-09 13:11 UTC, MaikoTan commented
確實，最好加個 cache（

2022-05-09 15:03 UTC, H4M5TER commented
这个 cache 它是需要 lock 的，我们是否已经有一个给 ci 用的 lock 了？

2022-05-15 12:01 UTC, H4M5TER commented
拆出来开仓库测过了
（然后忘记这回事了

2022-05-16 07:21 UTC, shigma requested changes

2022-05-16 07:21 UTC, shigma commented on .github/workflows/backlog.yml
> +          token: ${{ secrets.BACKLOG_PAT }}
```suggestion
          token: ${{ secrets.WORKFLOW_TOKEN }}
```

2022-05-16 07:21 UTC, shigma commented on .github/workflows/backlog.yml
> +      - "demilestoned"
引号删掉吧

2022-05-16 16:04 UTC, merged