updates for docker-compose.yml
koishijs/koishi pull request #91
Opened 2020-08-26 02:29 UTC by purerosefallen

1. In Mirai-based CQHttp docker images, `stdin_open` should be added for typing in captcha codes. Use `docker attach` to attach on it and type it in.
2. **TODO** websocket is more recommended as the default interacting method. I have no idea how to configure Koishi to use websocket as default, so not done. Perhaps you may set an `access_token` as default in both containers as well.

2020-08-26 05:06 UTC, NN708 commented
@purerosefallen Thank you for the pull request! However, I think we usually use `docker run -it` for an interactive shell. Why is tty (`-t`) not needed in this case?

2020-08-26 05:18 UTC, masnn commented
this is `docker-compose.yml` . containers start by `docker-compose up`, not directly by `docker run`

2020-08-26 05:20 UTC, NN708 commented
Yes, but `stdin_open: true` only means `-i`.

2020-08-26 05:21 UTC, NN708 commented
Have you tested that? Perhaps `tty: true` is needed?

2020-08-26 05:22 UTC, masnn commented
typing a captcha doesn't need a tty which supports color and some other features. creating a tty is a waste of resources.

2020-08-26 05:31 UTC, NN708 commented
Well, I think it is not relevant to color. I will test it later.

2020-08-27 08:36 UTC, NN708 requested changes
The input do not work normally. Maybe `tty: true` is required.

2020-08-27 12:05 UTC, masnn commented
I think providing a /captcha route is better.

2020-08-28 06:08 UTC, purerosefallen commented
@NN708 I've tried on other environment with go-cqhttp and apps developed based on Koishi.js. When tty was specified it worked badly. I was even not able to go back to terminal after `docker-compose up -d`.

2021-02-27 05:43 UTC, closed without merging

2021-02-27 05:55 UTC, NN708 commented
Koishi v3 now support various platforms, so a docker-compose.yml for CQHTTP seems to be inappropriate. Maybe we should maintain a separate repository for more docker-compose.yml examples.