fix
koishijs/koishi pull request #93
Opened 2020-08-26 10:41 UTC by masnn

2020-08-26 11:04 UTC, Shigma requested changes

2020-08-26 11:04 UTC, Shigma commented on packages/plugin-teach/src/database/mongo.ts
> +    return dialogues.filter(value => {
为啥这段写了两遍

2020-08-27 04:25 UTC, masnn commented on packages/plugin-teach/src/database/mongo.ts
> +    return dialogues.filter(value => {
哪里两遍

2020-08-29 17:08 UTC, Shigma approved these changes

2020-08-29 17:08 UTC, merged