feat(help): add command prefix hints
koishijs/koishi pull request #996
Opened 2023-03-01 13:55 UTC by Seidko

close #989

2023-03-01 14:20 UTC, shigma requested changes

2023-03-01 14:20 UTC, shigma commented on plugins/common/help/src/index.ts
> +  const firstPrefix = session.app.config.prefix[0] ?? ''
```suggestion
  const firstPrefix = session.resolve(session.app.config.prefix)[0] ?? ''
```

2023-03-01 14:20 UTC, shigma commented on plugins/common/help/src/index.ts
> +  output.unshift(session.text('.global-prefix', [prefixes]))
我不太喜欢这一行：

1. 对大部分用户来说，prefix 是 `['']`，过滤完变成空数组，你这里没有处理
2. 即使 prefix 不是空串，那么大概率只有 1 个，这 1 个已经在下方显示了，不需要额外显示一行
3. 即使 prefix 不是空串且有多个，我认为采用第一个作为推荐是合理的，没必要告诉用户其他的是什么
4. 引号的逻辑也不够清晰，你想象一下显示的结果有多糟糕

2023-03-01 14:20 UTC, shigma commented on plugins/common/help/src/index.ts
> +  const firstPrefix = session.app.config.prefix[0] ?? ''
要考虑 prefix 可能对不同会话有不同的值。下面其实也要考虑，但我不想要下面的逻辑。

2023-03-01 14:22 UTC, Seidko commented on plugins/common/help/src/index.ts
> +  output.unshift(session.text('.global-prefix', [prefixes]))
哦对不起，这里一开始我考虑到了，但我忘记处理了

2023-03-01 14:24 UTC, Seidko commented
那我增加一个 option 用于显示有哪些可用的 prefix ？

2023-03-01 14:39 UTC, shigma commented
> 那我增加一个 option 用于显示有哪些可用的 prefix ？

看上面 234 点，我认为这一行是负优化。

2023-03-01 14:40 UTC, shigma commented
还有，这个 PR 只处理了全局帮助，没有处理子指令的显示。

2023-03-01 14:47 UTC, Seidko commented
> 还有，这个 PR 只处理了全局帮助，没有处理子指令的显示。

子指令的格式化不也是走 `formatCommands` 的吗（

2023-03-01 14:48 UTC, shigma commented
> > 还有，这个 PR 只处理了全局帮助，没有处理子指令的显示。
> 
> 子指令的格式化不也是走 `formatCommands` 的吗（

你说得对，那删掉多余的代码就行了。

2023-03-01 14:56 UTC, Seidko commented
我有一个问题，shortcut 不需要前缀是预期的吗？

2023-03-01 14:57 UTC, shigma commented
> 我有一个问题，shortcut 不需要前缀是预期的吗？

是的。

2023-03-01 14:57 UTC, shigma approved these changes

2023-03-01 14:59 UTC, Seidko commented
那就有一个问题，在 `en_US` 下是没有 shortcut 的，这个时候就需要前缀了，难道需要判断有没有 shortcut 来加上这个提示吗？
```
en_US    Type "help <command>" to see syntax and examples for a specific command.
zh_CN    输入“帮助 指令名”查看特定指令的语法和使用示例。
```

2023-03-01 15:01 UTC, shigma commented
可以统一把下面的改成 {prefix}help

2023-03-01 16:16 UTC, Anillc commented
不给另外的语言也加上吗

2023-03-02 23:53 UTC, MaikoTan commented
Should also add the prefix in all other languages.

2023-03-03 11:32 UTC, Seidko commented
Maiko 来加吧😂我真的做不到（

2023-03-03 12:00 UTC, shigma approved these changes

2023-03-03 12:05 UTC, merged